# Generated by Django 5.2.1 on 2026-09-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_cv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده\u200cشده"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="certificate",
            name="instructor_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Instructor (EN)"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="issuer_en",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Issuer (EN)"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Title (EN)"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="year_en",
            field=models.CharField(blank=True, max_length=20, verbose_name="Year (EN)"),
        ),
        migrations.AddField(
            model_name="experience",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (EN)"),
        ),
        migrations.AddField(
            model_name="experience",
            name="location_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Location (EN)"
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="organization_en",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Organization (EN)"
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="period_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Period (EN)"
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="role_en",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Role (EN)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="about_en",
            field=models.TextField(blank=True, verbose_name="About (EN)"),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Full name (EN)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="headline_en",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Headline (EN)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="location_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Location (EN)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tagline_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Tagline (EN)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="outcome_en",
            field=models.TextField(blank=True, verbose_name="Outcome (EN)"),
        ),
        migrations.AddField(
            model_name="project",
            name="problem_en",
            field=models.TextField(blank=True, verbose_name="Problem (EN)"),
        ),
        migrations.AddField(
            model_name="project",
            name="solution_en",
            field=models.TextField(blank=True, verbose_name="Solution (EN)"),
        ),
        migrations.AddField(
            model_name="project",
            name="summary_en",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Summary (EN)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Title (EN)"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Skill name (EN)"
            ),
        ),
        migrations.AddField(
            model_name="skillcategory",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Category name (EN)"
            ),
        ),
    ]
